// PropIQ CreditMemoPanel — LLM-generated credit memo display
import React, { useState } from 'react';

export default function CreditMemoPanel({ creditMemo, requestId, locality }) {
  const [copied, setCopied] = useState(false);

  if (!creditMemo) {
    return (
      <div style={{ padding: 16, textAlign: 'center', color: '#888780', fontSize: 13 }}>
        Credit memo generated after assessment. Use the <strong>/assess/narrate</strong> endpoint.
      </div>
    );
  }

  const { summary, recommendation, risk_narrative, key_points } = creditMemo;

  const copyText = `PROPIQ COLLATERAL CREDIT MEMO
Request ID: ${requestId || '—'} | Property: ${locality || '—'}

SUMMARY
${summary}

RECOMMENDATION
${recommendation}

RISK NARRATIVE
${risk_narrative}

KEY POINTS
${(key_points || []).map((p, i) => `${i + 1}. ${p}`).join('\n')}

Generated by PropIQ AI Collateral Intelligence Engine`;

  const handleCopy = () => {
    navigator.clipboard.writeText(copyText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const recColor = recommendation?.toLowerCase().includes('acceptable') && 
                   !recommendation?.toLowerCase().includes('marginal') ? '#0F6E56' :
                   recommendation?.toLowerCase().includes('marginal') ? '#BA7517' : '#A32D2D';

  return (
    <div>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between',
        alignItems: 'center', marginBottom: 14 }}>
        <div>
          <div style={{ fontSize: 13, fontWeight: 600, color: '#2C2C2A' }}>
            Credit File Note
          </div>
          <div style={{ fontSize: 11, color: '#888780', marginTop: 1 }}>
            Generated by Claude AI · ID: {requestId}
          </div>
        </div>
        <button onClick={handleCopy}
          style={{ padding: '6px 12px', background: copied ? '#E1F5EE' : '#F1EFE8',
            border: `1px solid ${copied ? '#9FE1CB' : '#D3D1C7'}`,
            borderRadius: 6, fontSize: 11, fontWeight: 500,
            color: copied ? '#085041' : '#444441', cursor: 'pointer',
            fontFamily: 'Inter, sans-serif', transition: 'all 0.2s' }}>
          {copied ? '✓ Copied' : '⎘ Copy'}
        </button>
      </div>

      {/* Recommendation — most important */}
      <div style={{ background: '#F7F6F2', border: `2px solid ${recColor}`,
        borderRadius: 10, padding: '12px 16px', marginBottom: 12 }}>
        <div style={{ fontSize: 10, fontWeight: 700, color: recColor,
          textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 5 }}>
          Recommendation
        </div>
        <div style={{ fontSize: 13, color: '#2C2C2A', lineHeight: 1.6, fontWeight: 500 }}>
          {recommendation}
        </div>
      </div>

      {/* Summary */}
      <div style={{ background: '#fff', border: '1px solid rgba(44,44,42,0.10)',
        borderRadius: 10, padding: '12px 16px', marginBottom: 10 }}>
        <div style={{ fontSize: 10, fontWeight: 700, color: '#534AB7',
          textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>
          Summary
        </div>
        <div style={{ fontSize: 12, color: '#5F5E5A', lineHeight: 1.7 }}>
          {summary}
        </div>
      </div>

      {/* Risk Narrative */}
      <div style={{ background: '#fff', border: '1px solid rgba(44,44,42,0.10)',
        borderRadius: 10, padding: '12px 16px', marginBottom: 10 }}>
        <div style={{ fontSize: 10, fontWeight: 700, color: '#A32D2D',
          textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>
          Risk Narrative
        </div>
        <div style={{ fontSize: 12, color: '#5F5E5A', lineHeight: 1.7 }}>
          {risk_narrative}
        </div>
      </div>

      {/* Key Points */}
      {key_points && key_points.length > 0 && (
        <div style={{ background: '#fff', border: '1px solid rgba(44,44,42,0.10)',
          borderRadius: 10, padding: '12px 16px' }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: '#0F6E56',
            textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 8 }}>
            Key Points
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {key_points.map((pt, i) => (
              <div key={i} style={{ display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                <div style={{ width: 18, height: 18, background: '#EEEDFE', borderRadius: '50%',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 9, fontWeight: 700, color: '#534AB7', flexShrink: 0, marginTop: 1 }}>
                  {i + 1}
                </div>
                <div style={{ fontSize: 12, color: '#5F5E5A', lineHeight: 1.6 }}>{pt}</div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}